### ISSUE TITLE
Conditionally render hero section illustrations

### ISSUE THREAD

**Issue by CIPHERTron** [CIPHERTron/kaagaz#36]
[Mobile Illustration](https://res.cloudinary.com/dzvmhmqr0/image/upload/v1636449965/assets/hero-mobile_f7kiqb.png)
[Desktop Illustration](https://res.cloudinary.com/dzvmhmqr0/image/upload/v1636449962/assets/hero-desktop_tdeypr.png)

We've to show the desktop illustration in desktop view whereas mobile illustration in mobile view

**Comment by ORKO06** [comment]
I would like to work on it.

**Comment by CIPHERTron** [comment]
#43 fixes this. Thus closing!
