### ISSUE TITLE
Fix LegacyCard design according to the design doc

### ISSUE THREAD

**Issue by CIPHERTron** [CIPHERTron/kaagaz#37]
[Design Doc](https://docs.google.com/document/d/1Ypb22UAWNxThmozclwhhCoej-2IQvME6pN-0OVfEl2w/edit?usp=sharing)

In [LegacyCard.ts](https://github.com/CIPHERTron/kaagaz/blob/main/components/LegacyCard.tsx), the design isn't in accordance with the design doc. You have to fi the typography of this particular component ACC. to the doc. The styles for the LegacyCard can be found [here](https://github.com/CIPHERTron/kaagaz/blob/main/styles/legacy.styles.ts)

**Comment by ORKO06** [comment]
I would like to work on this.
