### ISSUE TITLE
Increase spacing between profile photo and name in team page

### ISSUE THREAD

**Issue by CIPHERTron** [CIPHERTron/kaagaz#39]
page: https://kaagaz.org.in/team
component: https://github.com/CIPHERTron/kaagaz/blob/main/components/TeamCard.tsx
component styles: https://github.com/CIPHERTron/kaagaz/blob/main/styles/team.styles.ts
> A spacing of 8-10px will do

**Comment by Abhas-15** [comment]
@CIPHERTron I would like to work on this issue.

**Comment by CIPHERTron** [comment]
Heyy @Abhas-15 this issue has already been addressed in PR #41 
Gotta close this issue as of now. Thanks for your interest!
